# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ff4419578216a9d76c99db20f05caa3e5992c4e350a8f272fdc9c9c1ce12a3bd5415b61bf23b77bc61670e83075db66984abd2c0885615306e41f4f3788dea

test:
  secret_key_base: 87191546e99b5f80f66752fae6bacee4a1f078f2e09b0b68b297005f5057256f78610adb5a538392f7b55303ff0f9fe229e91113c86a28afe4b3385744d1f888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
